### PR TITLE
Updates locals block key name

### PR DESCRIPTION
**Pull request by tlynam**
Hi, I was looking into this issue https://github.com/excid3/simple_calendar/issues/235

Updating the block key name appears to resolve the issue for me locally.  Is someone else able to confirm?

### CODE REVIEW

**Comment by excid3** [comment]
LGTM 👍

**Comment by excid3** [comment]
I guess this may break all existing installs that have overridden the view templates. They would need to be updated to reference `passed_block` right?

**Comment by tlynam** [comment]
Ah, yes, I'm seeing that now that you mention it.  So `block` is available in Rails 5 and 6?

**Comment by excid3** [comment]
`block` is definitely in the list in Rails 6.

I think this is good to renamed this, but we will have to cut a minor or major release for this update since it'd be a breaking change for anyone who has customized the templates. 

I think that's a fair change. Do you?

**Comment by tlynam** [comment]
Absolutely, thank you for your help!

**Comment by excid3** [comment]
Just released this as v2.4.0

**Comment by tlynam** [comment]
Thank you so much @excid3!

**Comment by cecilian** [comment]
Hi, thank you for the fix.
Given that this is admittedly a breaking change for all those who had customized templates, I suggest that it would have been helpful to add in the changelog also a cue to those folks to update their templates as well 🙂

**Comment by excid3** [comment]
@cecilian It has been in the changelog since we released it: https://github.com/excid3/simple_calendar/blob/master/CHANGELOG.md#240

**Comment by cecilian** [comment]
@excid3 gosh sorry I guess I only read the first line 😓 
Please excuse me you both and keep up the good work!

**Pull request merged**
