### PR TITLE
fix bug on beginning of week & end of week

### PR DESCRIPTION
**Pull request by blackbiron**

### CODE REVIEW

**Comment by excid3** [comment]
Hey @blackbiron,

What is the bug and what's this change do?

**Comment by blackbiron** [comment]
Please refer to attachments and see the difference between. This appears on rails 5.0.0.1 (might be rails' issue but haven't checked it yet on rails 4) on ruby 2.3.1

before
after

**Comment by excid3** [comment]
Oh very interesting. I wonder why something that core would have changed. I'm going to do some testing with it and check it out as well.

From what I can tell, this just is an alias for the other method. I'm not entirely sure why this would be different between the two?
http://apidock.com/rails/v4.2.7/DateAndTime/Calculations/at_beginning_of_week

Going to do some fiddling and see what I find.

**Comment by excid3** [comment]
I just generated a new Rails 5 app and it correctly found the beginning of the week. Are you setting other options by chance?

**Comment by blackbiron** [comment]
i will check my settings etc and will let you know the result.

**Comment by blackbiron** [comment]
you're right!

I started fresh project using rails 5 and ruby 2.3.1, added simple_calendar and it's works as expected. It might be caused by any other gem/config. Though it's strange when got different results between original and alias method (experiencing this issue on two different projects)

**Comment by excid3** [comment]
That's interesting! I hope you don't run into too much trouble. It sounds like something monkey patched that method which is not good. Hopefully you don't have too much trouble figuring it out! Maybe you can fix remove that monkey patch and clean everything up nicely!

**Pull request closed without merging**
