### PR TITLE
Issue #291 Add rails7 to Appraisals

### PR DESCRIPTION
**Pull request by elhalvers**
## Add Rails 7 to Appraisals

I was able to follow the steps from the Appraisal gem and the GoRails video to add Rails 7 to the Appraisals file. I ran the Appraisal Rake test successfully on Rails 7.

I also ran the Appraisal Rake test on the other two Appraisal versions; 6.0 and 6.1. Neither passed. I set up a test folder and re-cloned the current simple_calendar repo and ran the Appraisal Rake tests on the existing Rails 6 and Rails 6.1 and they also failed.

I am wondering if this is related to the test/dummy app that was added recently. In the video, you mention something about that. I was not able to make changes to fix the rake test for 6 and 6.1 but I figure that can be another issue to fix. 😊

### CODE REVIEW

**Comment by elhalvers** [comment]
I also added Ruby 3.1 and Rails 7.0 to the ci.yml file which is issue #290. I was planning on adding this as a second pull request but it looks like maybe some of the Appraisals failures are due to Rails 7 not being part of the GitHub actions CI 😊

**Comment by elhalvers** [comment]
I'm going to try to get the rake tests to work on Rails 6 and 6.1 🙂

**Comment by excid3** [comment]
Need to add Ruby 3.2 as well now!

If you want to pair on this, hit me up on Discord and let's find a time to jump on Tuple and I can show you how to do it. 👍

**Comment by elhalvers** [comment]
Cool!

Will do!

: )

Eric

**Pull request closed without merging**
