### PR TITLE
Make 'Week' in week_calendar view transleatable

### PR DESCRIPTION
**Pull request by fwolfst**

### CODE REVIEW

**Comment by excid3** [comment]
Awesome, thanks @fwolfst!

Do you think there's anything else that needs updating? I was thinking I should cut a new release with these updates soon.

**Comment by fwolfst** [comment]
@excid3 besides the "pay me (automatically)"-button I see no important missing feature ;)

I am just minimally toying around with the gem. The obvious things would be support for events spanning multiple days to appear as connected boxes (instead of being individually rendered within each day). But thats an expensive change, most likely requiring some freaky heuristics regarding within-day-event ordering etc.
As a start a helper could be implemented that spits out whether the event started earlier than this day and ends later than this day (`#start_before_this_day?`, `#end_after_this_day?` or "negatively": `#starts_this_day?`, `#ends_this_day?`).

The other change that I did locally was to have an additional first column in month calenders to render the week number (https://github.com/ecovillage/sevencal/blob/e533ba244470c76e8e1375c01afc9d3f27c14bd0/app/views/simple_calendar/_month_calendar.html.erb#L21). Would be a nice-to-have but its a two-line change to implement oneself.

Do not see any low-hanging fruits. The i18n keys could be mentioned in the README. Can PR a for that next week if you'd like. Thanks for your efforts!

**Comment by excid3** [comment]
Yeah, I never got around to multi-day events because of it being a little tricky. 

I think if you sort the events by their start date, then it should be fine as you can stack them that way. Then you can set a background on it like GMail does. And if you wanted to put like rounded corners on the edges, I think you'd just check if `day == event.start_time.to_date` to determine if it was the first day of a multi-day event. And you could do the same for the latter.

That's actually a feature I would love to do and I feel like it could make for an interesting screencast for GoRails.

Would love that PR if you have time next week. 👍

**Comment by fwolfst** [comment]
> I think if you sort the events by their start date, then it should be fine as you can stack them that way. Then you can set a background on it like GMail does. And if you wanted to put like rounded corners on the edges, I think you'd just check if `day == event.start_time.to_date` to determine if it was the first day of a multi-day event. And you could do the same for the latter.

I think its not as easy as that. If you want to be "space-efficient"/optimal I believe its a NP-hard stacking problem but with many heuristics that are good-enough. While I love these kinds of problems, it unfortunately totally out of scope for my current project. A GoRails screencast about it would be cool!

**Comment by fwolfst** [comment]
> Would love that PR if you have time next week for the i18n keys. +1

done (https://github.com/excid3/simple_calendar/pull/252).

**Pull request merged**
