### PR TITLE
Show events spanning more than one day

### PR DESCRIPTION
**Pull request by TuxmAL**
I work with events read from a vCal file and I needed to show events spanning more than one day in a different look. So I modified _Event_ object to support  **:simple_calendar_range_date** method and to expose **event_start_date**  and **event_end_date** property.
If **:simple_calendar_range_date** method is found then I check if event spans over a date range (**event_start_date**..**event_end_date**) and then I sort events selected by start date.
(Warning: it may result that period with _same_ start date are **not** ordered by end date!)
if **:simple_calendar_range_date** method is not found, then, as before, **:simple_calendar_start_time** method is checked (single date events), else events is passed as is.

### CODE REVIEW

**Comment by rodrigoargumedo** [comment]
This looks very promising after all. Can you add some test cases once #86 is merged? That would be really helpful to test against those functionalities.

**Comment by rodrigoargumedo** [comment]
This looks very promising after all. Can you add some test cases once #87 is merged? That would be really helpful to test against those functionalities.

**Comment by TuxmAL** [comment]
I'll be on vacation the next week, but I'll add some test as soon as possible!


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Rodrigo Argumedo <notifications@github.com> 
Data: 26/06/2015  08:05  (GMT+01:00) 
A: excid3/simple_calendar <simple_calendar@noreply.github.com> 
Cc: Antonio Liccardo <tuxmal@tiscali.it> 
Oggetto: Re: [simple_calendar] Show events spanning more than one day (#58) 
 
This looks very promising after all. Can you add some test cases once #87 is merged? That would be really helpful to test against those functionalities.

**Comment by rodrigoargumedo** [comment]
:smile: :+1:





On Sat, Jun 27, 2015 at 3:50 AM -0700, "Antonio Liccardo" <notifications@github.com> wrote:
I'll be on vacation the next week, but I'll add some test as soon as possible!


Inviato da Samsung Mobile

-------- Messaggio originale --------
Da: Rodrigo Argumedo <notifications@github.com>
Data: 26/06/2015  08:05  (GMT+01:00)
A: excid3/simple_calendar <simple_calendar@noreply.github.com>
Cc: Antonio Liccardo <tuxmal@tiscali.it>
Oggetto: Re: [simple_calendar] Show events spanning more than one day (#58)

This looks very promising after all. Can you add some test cases once #87 is merged? That would be really helpful to test against those functionalities.

—
Reply to this email directly or view it on GitHub.



---

**Comment by Exoth** [comment]
It looks to me that if `starts_at` is `2015-10-10 00:00` and `ends_at` is `2015-10-11 00:00`, event is gonna be displayed at both `2015-10-10` and `2015-10-11`, but I would expect it to be only `2015-10-10`.

**Comment by TuxmAL** [comment]
Hi @Exoth that's my fault, because I'm using an ical/vcal file for my project and, as stated into the RFC5545, 
> the 'dtend' property for a 'event' calendar component specifies  the non-inclusive end of the event. 

So automagically the ends_at works as expected for me. Obviously that's not true for others.
Now I'm engaged in another project, so while I find some free time to correct this, you my find easier to do this correction yourself: 

```ruby
def simple_calendar_range_date
  (#{config[:attribute].first.to_s}.to_date...#{config[:attribute].last.to_s}.to_date)
end
```
into model_additions.rb

**Comment by TuxmAL** [comment]
oops, I closed it inadvertently!

**Comment by rodrigoargumedo** [comment]
Can you rebase those merge commits?

**Comment by TuxmAL** [comment]
@rodrigoargumedo I tried to rebase (git rebase and then git push) but nothing seems to change, pleasy may you explain what should I do?

**Comment by TuxmAL** [comment]
@rodrigoargumedo after some tribulation this is what I have obtained, hope it will help, otherwise feel free to ask more!

**Comment by rodrigoargumedo** [comment]
Can you add me as a contributor into your fork? It doesn't seem getting push access to it.

**Comment by rodrigoargumedo** [comment]
I may try to rebase some empty commits that you've made earlier and commit them again.

**Comment by TuxmAL** [comment]
Ok @rodrigoargumedo, now you should be a collaborator on my fork.
Thanks for helping me, as I'm not so versed into git (and I'm scared to make some nasty move)!

**Comment by beranPro** [comment]
+1 +1 +1

**Comment by Zai** [comment]
+1

**Comment by excid3** [comment]
I'm going to try diving into tackling this on the 2.0 branch since so much has changed. Sorry for letting this issue stay open for so long. :(

**Comment by excid3** [comment]
@JurgenJocubeit we added support for multi-day events a couple years ago: https://github.com/excid3/simple_calendar/commit/fac80a67d9ee58e2a31d3a6a4fd8ec8034e5e1a6

You just specify the `end_time` attribute in the options to enable it.

**Pull request closed without merging**
