### PR TITLE
make tests pass by requiring simple calendar

### PR DESCRIPTION
**Pull request by sidtri**

### CODE REVIEW

**Comment by excid3** [comment]
@sidtri what command are you using to run the tests? Mine wasn't complaining without this. Just curious!

**Comment by sidtri** [comment]
just a travis stuff

**Comment by excid3** [comment]
I believe it's passing without that require line actually. https://travis-ci.org/excid3/simple_calendar/builds/68528759

**Comment by sidtri** [comment]
May be, but tests are failing istn local while running without require
simple calendar. So it place it over there

**Pull request closed without merging**
