### PR TITLE
Feature/today button + fix for previous navigation button

### PR DESCRIPTION
**Pull request by EmCousin**
This Pull Request addresses https://github.com/excid3/simple_calendar/issues/271 and https://github.com/excid3/simple_calendar/issues/272

- [x] Added a "today" button in addition to "previous" and "next" (https://github.com/excid3/simple_calendar/issues/271)
- [x] Fixed "previous" button for generic calendars (https://github.com/excid3/simple_calendar/issues/272)
- [x] Added tests to cover these improvements + wrote some overdue tests for week and month calendars
- [x] Updated documentation (`README.md`) 
- [x] Updated changelog (`CHANGELOG.md`)

### CODE REVIEW

**Comment by excid3** [comment]
cc @cjilbert504

**Comment by EmCousin** [comment]
@excid3 I'm not entirely sure to understand what's going on with CI :

```
 You are trying to install in deployment mode after changing
  your Gemfile. Run `bundle install` elsewhere and add the
  updated gemfiles/rails_6_1.gemfile.lock to version control.
```

This PR didn't touch the Gemfile. Is there anything I'm missing?

**Comment by rodrigoargumedo** [comment]
Did you make an update to Rails 6.1.x Gemfile?

**Comment by EmCousin** [comment]
Hi @rodrigoargumedo, not that I know of. I see that the repo has multiple Gemfiles so that CircleCI runs the tests over multiple environments, but this branch didn't touch any of them. Should it?

**Comment by zwfisher** [comment]
this would be a nice change to go with new tailwind calendars, any word on getting those tests to pass?

**Pull request closed without merging**
